name: Deploy Project
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Inject Secrets
      env:
        FB_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FB_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FB_URL: ${{ secrets.FIREBASE_DB_URL }}
        FB_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FB_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FB_SENDER: ${{ secrets.FIREBASE_SENDER_ID }}
        FB_APP: ${{ secrets.FIREBASE_APP_ID }}
      run: |
        sed -i "s|CONF_API_KEY|$FB_KEY|g" index.html
        sed -i "s|CONF_AUTH_DOMAIN|$FB_DOMAIN|g" index.html
        sed -i "s|CONF_DB_URL|$FB_URL|g" index.html
        sed -i "s|CONF_PROJECT_ID|$FB_ID|g" index.html
        sed -i "s|CONF_STORAGE_BUCKET|$FB_BUCKET|g" index.html
        sed -i "s|CONF_SENDER_ID|$FB_SENDER|g" index.html
        sed -i "s|CONF_APP_ID|$FB_APP|g" index.html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        force_orphan: true
